# Generated by Django 3.2 on 2021-05-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_shop.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_shop.user')),
            ],
        ),
    ]
