# Generated by Django 3.2 on 2021-05-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0004_auto_20210503_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=None),
        ),
    ]
