# Generated by Django 3.2 on 2021-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0006_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='productid',
        ),
        migrations.AddField(
            model_name='orders',
            name='product_detail',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
