# Generated by Django 3.2 on 2021-05-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_shop', '0007_auto_20210505_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
